gui:
  theme:
    activeBorderColor:
      - bold
      - red
    inactiveBorderColor:
      - white
    optionsTextColor:
      - yellow
    selectedLineBgColor:
      - black # set to `default` to have no background colour
    selectedRangeBgColor:
      - default
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red

  showFileTree: true # for rendering changes files in a tree format
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showRandomTip: false
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: true
  showIcons: true

disableStartupPopups: true
notARepository: "skip" # one of: 'prompt' | 'create' | 'skip'
os:
  editCommand: "nvim"
git:
  paging:
    colorArg: never
    pager: delta --paging=never
